CREATE TABLE 
IF NOT EXISTS
    users(
        usersEmail VARCHAR(50) NOT NULL PRIMARY KEY,
        usersPassword VARCHAR(50) NOT NULL,
        usersGender VARCHAR(1) NOT NULL,
        usersLastname VARCHAR(50) NOT NULL,
        usersFirstname VARCHAR(50) NOT NULL,
        usersCreationDate DATE NOT NULL,
        usersLastConnexion DATE NOT NULL,
        usersRole SMALLINT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    producer(
        producerId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        producerDesc VARCHAR(1500) NOT NULL,
        producerSiretNum VARCHAR(14) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    favorite_producer(
        usersId VARCHAR(50) NOT NULL,
        producerId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    user_producer(
        usersId VARCHAR(50) NOT NULL,
        producerId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    orders(
        ordersId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        usersId VARCHAR(50) NOT NULL,
        ordersTotalCost INTEGER NOT NULL,
        ordersDate DATE NOT NULL,
        ordersStatus VARCHAR(1) NOT NULL
    );
        
CREATE TABLE 
IF NOT EXISTS
    orders_items(
        ordersItemsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        ordersId INTEGER NOT NULL,
        productId INTEGER NOT NULL,
        ordersItemsQuantity INTEGER NOT NULL,
        ordersItemsTotalCost FLOAT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    basket_items(
        basketItemsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        usersId VARCHAR(50) NOT NULL,
        productId INTEGER NOT NULL,
        basketItemsQuantity INTEGER NOT NULL,
        basketItemsTotalCost FLOAT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    product(
        productId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        producerId INTEGER NOT NULL,
        categoryId INTEGER NOT NULL,
        subcategoryId INTEGER NOT NULL,
        productName VARCHAR(100) NOT NULL,
        productPrice FLOAT NOT NULL,
        productDesc VARCHAR(1500) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    assorte(
        productId1 INTEGER NOT NULL,
        productId2 INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    favorite_product(
        usersId VARCHAR(50) NOT NULL,
        productId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    category(
        categoryId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        categoryName VARCHAR(50) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    subcategory(
        subcategoryId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        subcategoryName VARCHAR(100) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    partners(
        productId INTEGER NOT NULL,
        subcategoryId VARCHAR(100) NOT NULL 
    );
    
CREATE TABLE 
IF NOT EXISTS
    events(
        eventsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        eventsLocation VARCHAR(100) NOT NULL,
        eventsDate DATE NOT NULL,
        eventsName VARCHAR(100) NOT NULL,
        eventsDesc VARCHAR(1500) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    go_to_events(
        usersId VARCHAR(50) NOT NULL,
        eventsId INTEGER NOT NULL 
    );