CREATE TABLE 
IF NOT EXISTS
    users(
        usersEmail VARCHAR(64) NOT NULL PRIMARY KEY,
        usersPassword VARCHAR(64) NOT NULL,
        usersGender VARCHAR(1) NOT NULL,
        usersLastname VARCHAR(50) NOT NULL,
        usersFirstname VARCHAR(50) NOT NULL,
        usersCreationDate DATE NOT NULL,
        usersLastConnexion DATE NOT NULL,
        usersRole SMALLINT NOT NULL,
        usersStatus VARCHAR(10) NOT NULL,
        usersProfilPicture VARCHAR(500)
    );

CREATE TABLE 
IF NOT EXISTS
    producer(
        producerId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        producerDesc VARCHAR(1500),
        producerLocalisation VARCHAR(100),
        producerSiretNum VARCHAR(14) NOT NULL,
        producerStatus VARCHAR(10) NOT NULL,
        producerCreationDate DATE NOT NULL DEFAULT CURRENT_DATE,
        producerLastConnexion DATE NOT NULL DEFAULT CURRENT_DATE
    );

CREATE TABLE 
IF NOT EXISTS
    favorite_producer(
        usersId VARCHAR(50) NOT NULL,
        producerId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    user_producer(
        usersId VARCHAR(50) NOT NULL,
        producerId INTEGER NOT NULL 
    );

CREATE TABLE
IF NOT EXISTS
    image_producer(
        producerId INTEGER NOT NULL,
        imageProducerUrl VARCHAR(500) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    association(
        associationId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        associationLocationOffice VARCHAR(100) NOT NULL,
        associationValues VARCHAR(1500),
        associationTestimony VARCHAR(1500),
        associationDescHome VARCHAR(1500) NOT NULL,
        associationDescAbout VARCHAR(1500) NOT NULL,
        associationEmail VARCHAR(50) NOT NULL,
        associationNum VARCHAR(15) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    user_association(
        usersId VARCHAR(50) NOT NULL,
        associationId INTEGER NOT NULL 
    );

CREATE TABLE
IF NOT EXISTS
    image_association(
        associationId INTEGER NOT NULL,
        imageAssociationUrl VARCHAR(500) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    orders(
        ordersId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        usersId VARCHAR(50) NOT NULL,
        ordersTotalCost FLOAT NOT NULL,
        ordersDate DATE NOT NULL,
        ordersStatus VARCHAR(1)
    );
        
CREATE TABLE 
IF NOT EXISTS
    orders_items(
        ordersItemsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        ordersId INTEGER NOT NULL,
        productId INTEGER NOT NULL,
        ordersItemsQuantity INTEGER NOT NULL,
        ordersItemsTotalCost FLOAT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    basket_items(
        basketItemsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        usersId VARCHAR(50) NOT NULL,
        productId INTEGER NOT NULL,
        basketItemsQuantity INTEGER NOT NULL,
        basketItemsTotalCost FLOAT NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    product(
        productId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        producerId INTEGER NOT NULL,
        categoryId INTEGER NOT NULL,
        subcategoryId INTEGER,
        productName VARCHAR(100) NOT NULL,
        productPrice FLOAT NOT NULL,
        productDesc VARCHAR(1500) NOT NULL,
        productStatus VARCHAR(10) NOT NULL,
        productPicture VARCHAR(500)
    );

CREATE TABLE 
IF NOT EXISTS
    assorte(
        productId1 INTEGER NOT NULL,
        productId2 INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    favorite_product(
        usersId VARCHAR(50) NOT NULL,
        productId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    category(
        categoryId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        categoryName VARCHAR(50) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    subcategory(
        subcategoryId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        categoryId INTEGER NOT NULL,
        subcategoryName VARCHAR(100) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    partners(
        productId INTEGER NOT NULL,
        subcategoryId VARCHAR(100) NOT NULL 
    );
    
CREATE TABLE 
IF NOT EXISTS
    events(
        eventsId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        eventsLocation VARCHAR(100) NOT NULL,
        eventsDate DATE NOT NULL,
        eventsName VARCHAR(100) NOT NULL,
        eventsDesc VARCHAR(1500) NOT NULL,
        eventsStatus VARCHAR(10) NOT NULL
    );

CREATE TABLE 
IF NOT EXISTS
    go_to_events(
        producerId INTEGER NOT NULL,
        eventsId INTEGER NOT NULL 
    );

CREATE TABLE 
IF NOT EXISTS
    comment(
        commentId INTEGER NOT NULL PRIMARY KEY generated by default as identity,
        usersId INTEGER NOT NULL,
        productId INTEGER NOT NULL,
        commentTxt VARCHAR(2000) NOT NULL,
        commentDate DATE NOT NULL
    );
        
